### ISSUE TITLE
regression test v3.0.0

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#417]
- users
   - [x] new
   - [x] edit
   - [x] send password (via login view forgot password link)
- races
   - [x] new
   - [x] edit
   - [x] import races (tools popup)
   - [x] export CSV
   - [x] import results - no overwrite (race popup) (#424)
   - [x] import results - overwrite (race popup)
      - [x] csv 
      - [x] xlsx (#422)
      - [x] xls
      - [x] txt
   - [x] edit participants navigation (race popup)
   - [x] view series results navigation (race popup)
- members
   - [x] edit
   - [x] export CSV
   - [x] import members from file
   - [x] import members from RunSignUp (#415)
- edit participants
   - [x] new
   - [x] edit (note unless 'definite' edit window does not bring up result name)
   - [x] delete
   - [ ] edit member age update (same name two people)
   - [x] member pulldown
   - [x] confirm (name present)
   - [x] confirm (not included indicated)
   - [x] tabulate
   - [x] export CSV (note this view only exports the results which are currently displayed)
- series
   - [x] new
   - [x] edit
   - [x] delete
   - [x] export CSV
- divisions
   - [x] new
   - [x] edit
   - [x] delete
   - [x] export CSV
- Results (menu) popup (user view)
   - [x] table view
   - [x] chart view (update d3.js before testing)
- [x] Standings (menu) popup
- [ ] automated copy to new year: series, divisions, races (requires #375)
- results analysis
   - [x] results analysis collection
   - [x] results analysis summary display
   - [x] results analysis individual results display
